server:
  port: 8081

spring:
  application:
    name: fm-router
  datasource:
    url: jdbc:mysql://123.249.21.100:3306/fm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

  # enable swagger
springdoc:
  swagger-ui:
    enabled: true