// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FmResProtocol.proto

package com.baiyina.fmcommon.protocol.protobuf;

/**
 * @author ll
 */
public final class FmResponseProto {
  private FmResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FmResProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.FmResProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 响应的唯一标识符
     * </pre>
     *
     * <code>int64 response_key = 1;</code>
     * @return The responseKey.
     */
    long getResponseKey();

    /**
     * <pre>
     * 请求的ID
     * </pre>
     *
     * <code>int32 request_id = 2;</code>
     * @return The requestId.
     */
    int getRequestId();

    /**
     * <pre>
     * 响应的消息内容
     * </pre>
     *
     * <code>string resp_msg = 3;</code>
     * @return The respMsg.
     */
    java.lang.String getRespMsg();
    /**
     * <pre>
     * 响应的消息内容
     * </pre>
     *
     * <code>string resp_msg = 3;</code>
     * @return The bytes for respMsg.
     */
    com.google.protobuf.ByteString
        getRespMsgBytes();

    /**
     * <pre>
     * 响应的状态码
     * </pre>
     *
     * <code>int32 status_code = 4;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <pre>
     * 响应的类型
     * </pre>
     *
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * <pre>
   * 响应消息的协议定义
   * </pre>
   *
   * Protobuf type {@code protocol.FmResProto}
   */
  public static final class FmResProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.FmResProto)
      FmResProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FmResProto.newBuilder() to construct.
    private FmResProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FmResProto() {
      respMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FmResProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.internal_static_protocol_FmResProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.internal_static_protocol_FmResProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.class, com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.Builder.class);
    }

    public static final int RESPONSE_KEY_FIELD_NUMBER = 1;
    private long responseKey_;
    /**
     * <pre>
     * 响应的唯一标识符
     * </pre>
     *
     * <code>int64 response_key = 1;</code>
     * @return The responseKey.
     */
    @java.lang.Override
    public long getResponseKey() {
      return responseKey_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private int requestId_;
    /**
     * <pre>
     * 请求的ID
     * </pre>
     *
     * <code>int32 request_id = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }

    public static final int RESP_MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object respMsg_;
    /**
     * <pre>
     * 响应的消息内容
     * </pre>
     *
     * <code>string resp_msg = 3;</code>
     * @return The respMsg.
     */
    @java.lang.Override
    public java.lang.String getRespMsg() {
      java.lang.Object ref = respMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        respMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应的消息内容
     * </pre>
     *
     * <code>string resp_msg = 3;</code>
     * @return The bytes for respMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRespMsgBytes() {
      java.lang.Object ref = respMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_CODE_FIELD_NUMBER = 4;
    private int statusCode_;
    /**
     * <pre>
     * 响应的状态码
     * </pre>
     *
     * <code>int32 status_code = 4;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <pre>
     * 响应的类型
     * </pre>
     *
     * <code>int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseKey_ != 0L) {
        output.writeInt64(1, responseKey_);
      }
      if (requestId_ != 0) {
        output.writeInt32(2, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(respMsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, respMsg_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(4, statusCode_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseKey_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, responseKey_);
      }
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(respMsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, respMsg_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, statusCode_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto)) {
        return super.equals(obj);
      }
      com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto other = (com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto) obj;

      if (getResponseKey()
          != other.getResponseKey()) return false;
      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getRespMsg()
          .equals(other.getRespMsg())) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (getType()
          != other.getType()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseKey());
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (37 * hash) + RESP_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getRespMsg().hashCode();
      hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应消息的协议定义
     * </pre>
     *
     * Protobuf type {@code protocol.FmResProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.FmResProto)
        com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.internal_static_protocol_FmResProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.internal_static_protocol_FmResProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.class, com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.Builder.class);
      }

      // Construct using com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseKey_ = 0L;

        requestId_ = 0;

        respMsg_ = "";

        statusCode_ = 0;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.internal_static_protocol_FmResProto_descriptor;
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto getDefaultInstanceForType() {
        return com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto build() {
        com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto buildPartial() {
        com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto result = new com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto(this);
        result.responseKey_ = responseKey_;
        result.requestId_ = requestId_;
        result.respMsg_ = respMsg_;
        result.statusCode_ = statusCode_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto) {
          return mergeFrom((com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto other) {
        if (other == com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto.getDefaultInstance()) return this;
        if (other.getResponseKey() != 0L) {
          setResponseKey(other.getResponseKey());
        }
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        if (!other.getRespMsg().isEmpty()) {
          respMsg_ = other.respMsg_;
          onChanged();
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                responseKey_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                requestId_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                respMsg_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                statusCode_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                type_ = input.readInt32();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long responseKey_ ;
      /**
       * <pre>
       * 响应的唯一标识符
       * </pre>
       *
       * <code>int64 response_key = 1;</code>
       * @return The responseKey.
       */
      @java.lang.Override
      public long getResponseKey() {
        return responseKey_;
      }
      /**
       * <pre>
       * 响应的唯一标识符
       * </pre>
       *
       * <code>int64 response_key = 1;</code>
       * @param value The responseKey to set.
       * @return This builder for chaining.
       */
      public Builder setResponseKey(long value) {
        
        responseKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的唯一标识符
       * </pre>
       *
       * <code>int64 response_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseKey() {
        
        responseKey_ = 0L;
        onChanged();
        return this;
      }

      private int requestId_ ;
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object respMsg_ = "";
      /**
       * <pre>
       * 响应的消息内容
       * </pre>
       *
       * <code>string resp_msg = 3;</code>
       * @return The respMsg.
       */
      public java.lang.String getRespMsg() {
        java.lang.Object ref = respMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          respMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 响应的消息内容
       * </pre>
       *
       * <code>string resp_msg = 3;</code>
       * @return The bytes for respMsg.
       */
      public com.google.protobuf.ByteString
          getRespMsgBytes() {
        java.lang.Object ref = respMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应的消息内容
       * </pre>
       *
       * <code>string resp_msg = 3;</code>
       * @param value The respMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRespMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        respMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的消息内容
       * </pre>
       *
       * <code>string resp_msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRespMsg() {
        
        respMsg_ = getDefaultInstance().getRespMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的消息内容
       * </pre>
       *
       * <code>string resp_msg = 3;</code>
       * @param value The bytes for respMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRespMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        respMsg_ = value;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <pre>
       * 响应的状态码
       * </pre>
       *
       * <code>int32 status_code = 4;</code>
       * @return The statusCode.
       */
      @java.lang.Override
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <pre>
       * 响应的状态码
       * </pre>
       *
       * <code>int32 status_code = 4;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的状态码
       * </pre>
       *
       * <code>int32 status_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 响应的类型
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 响应的类型
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应的类型
       * </pre>
       *
       * <code>int32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.FmResProto)
    }

    // @@protoc_insertion_point(class_scope:protocol.FmResProto)
    private static final com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto();
    }

    public static com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FmResProto>
        PARSER = new com.google.protobuf.AbstractParser<FmResProto>() {
      @java.lang.Override
      public FmResProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FmResProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FmResProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.baiyina.fmcommon.protocol.protobuf.FmResponseProto.FmResProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_FmResProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_FmResProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FmResProtocol.proto\022\010protocol\"k\n\nFmRes" +
      "Proto\022\024\n\014response_key\030\001 \001(\003\022\022\n\nrequest_i" +
      "d\030\002 \001(\005\022\020\n\010resp_msg\030\003 \001(\t\022\023\n\013status_code" +
      "\030\004 \001(\005\022\014\n\004type\030\005 \001(\005B9\n&com.baiyina.fmco" +
      "mmon.protocol.protobufB\017FmResponseProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_FmResProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_FmResProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_FmResProto_descriptor,
        new java.lang.String[] { "ResponseKey", "RequestId", "RespMsg", "StatusCode", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
