// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FmReqProtocol.proto

package com.baiyina.fmcommon.protocol.protobuf;

/**
 * @author ll
 */
public final class FmRequestProto {
  private FmRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FmReqProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.FmReqProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求的唯一标识符
     * </pre>
     *
     * <code>int64 request_key = 1;</code>
     * @return The requestKey.
     */
    long getRequestKey();

    /**
     * <pre>
     * 请求的ID
     * </pre>
     *
     * <code>int32 request_id = 2;</code>
     * @return The requestId.
     */
    int getRequestId();

    /**
     * <pre>
     * 请求的消息内容
     * </pre>
     *
     * <code>string req_msg = 3;</code>
     * @return The reqMsg.
     */
    java.lang.String getReqMsg();
    /**
     * <pre>
     * 请求的消息内容
     * </pre>
     *
     * <code>string req_msg = 3;</code>
     * @return The bytes for reqMsg.
     */
    com.google.protobuf.ByteString
        getReqMsgBytes();

    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * <pre>
   * 请求消息的协议定义
   * </pre>
   *
   * Protobuf type {@code protocol.FmReqProto}
   */
  public static final class FmReqProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.FmReqProto)
      FmReqProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FmReqProto.newBuilder() to construct.
    private FmReqProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FmReqProto() {
      reqMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FmReqProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.internal_static_protocol_FmReqProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.internal_static_protocol_FmReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.class, com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.Builder.class);
    }

    public static final int REQUEST_KEY_FIELD_NUMBER = 1;
    private long requestKey_;
    /**
     * <pre>
     * 请求的唯一标识符
     * </pre>
     *
     * <code>int64 request_key = 1;</code>
     * @return The requestKey.
     */
    @java.lang.Override
    public long getRequestKey() {
      return requestKey_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private int requestId_;
    /**
     * <pre>
     * 请求的ID
     * </pre>
     *
     * <code>int32 request_id = 2;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }

    public static final int REQ_MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object reqMsg_;
    /**
     * <pre>
     * 请求的消息内容
     * </pre>
     *
     * <code>string req_msg = 3;</code>
     * @return The reqMsg.
     */
    @java.lang.Override
    public java.lang.String getReqMsg() {
      java.lang.Object ref = reqMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求的消息内容
     * </pre>
     *
     * <code>string req_msg = 3;</code>
     * @return The bytes for reqMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReqMsgBytes() {
      java.lang.Object ref = reqMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestKey_ != 0L) {
        output.writeInt64(1, requestKey_);
      }
      if (requestId_ != 0) {
        output.writeInt32(2, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqMsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reqMsg_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestKey_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestKey_);
      }
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqMsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reqMsg_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto)) {
        return super.equals(obj);
      }
      com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto other = (com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto) obj;

      if (getRequestKey()
          != other.getRequestKey()) return false;
      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getReqMsg()
          .equals(other.getReqMsg())) return false;
      if (getType()
          != other.getType()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestKey());
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (37 * hash) + REQ_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getReqMsg().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求消息的协议定义
     * </pre>
     *
     * Protobuf type {@code protocol.FmReqProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.FmReqProto)
        com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.internal_static_protocol_FmReqProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.internal_static_protocol_FmReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.class, com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.Builder.class);
      }

      // Construct using com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestKey_ = 0L;

        requestId_ = 0;

        reqMsg_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.internal_static_protocol_FmReqProto_descriptor;
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto getDefaultInstanceForType() {
        return com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto build() {
        com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto buildPartial() {
        com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto result = new com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto(this);
        result.requestKey_ = requestKey_;
        result.requestId_ = requestId_;
        result.reqMsg_ = reqMsg_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto) {
          return mergeFrom((com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto other) {
        if (other == com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto.getDefaultInstance()) return this;
        if (other.getRequestKey() != 0L) {
          setRequestKey(other.getRequestKey());
        }
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        if (!other.getReqMsg().isEmpty()) {
          reqMsg_ = other.reqMsg_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestKey_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                requestId_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                reqMsg_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                type_ = input.readInt32();

                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long requestKey_ ;
      /**
       * <pre>
       * 请求的唯一标识符
       * </pre>
       *
       * <code>int64 request_key = 1;</code>
       * @return The requestKey.
       */
      @java.lang.Override
      public long getRequestKey() {
        return requestKey_;
      }
      /**
       * <pre>
       * 请求的唯一标识符
       * </pre>
       *
       * <code>int64 request_key = 1;</code>
       * @param value The requestKey to set.
       * @return This builder for chaining.
       */
      public Builder setRequestKey(long value) {
        
        requestKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的唯一标识符
       * </pre>
       *
       * <code>int64 request_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestKey() {
        
        requestKey_ = 0L;
        onChanged();
        return this;
      }

      private int requestId_ ;
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @return The requestId.
       */
      @java.lang.Override
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的ID
       * </pre>
       *
       * <code>int32 request_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reqMsg_ = "";
      /**
       * <pre>
       * 请求的消息内容
       * </pre>
       *
       * <code>string req_msg = 3;</code>
       * @return The reqMsg.
       */
      public java.lang.String getReqMsg() {
        java.lang.Object ref = reqMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求的消息内容
       * </pre>
       *
       * <code>string req_msg = 3;</code>
       * @return The bytes for reqMsg.
       */
      public com.google.protobuf.ByteString
          getReqMsgBytes() {
        java.lang.Object ref = reqMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求的消息内容
       * </pre>
       *
       * <code>string req_msg = 3;</code>
       * @param value The reqMsg to set.
       * @return This builder for chaining.
       */
      public Builder setReqMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的消息内容
       * </pre>
       *
       * <code>string req_msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqMsg() {
        
        reqMsg_ = getDefaultInstance().getReqMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的消息内容
       * </pre>
       *
       * <code>string req_msg = 3;</code>
       * @param value The bytes for reqMsg to set.
       * @return This builder for chaining.
       */
      public Builder setReqMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqMsg_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.FmReqProto)
    }

    // @@protoc_insertion_point(class_scope:protocol.FmReqProto)
    private static final com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto();
    }

    public static com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FmReqProto>
        PARSER = new com.google.protobuf.AbstractParser<FmReqProto>() {
      @java.lang.Override
      public FmReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FmReqProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FmReqProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.baiyina.fmcommon.protocol.protobuf.FmRequestProto.FmReqProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_FmReqProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_FmReqProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FmReqProtocol.proto\022\010protocol\"T\n\nFmReq" +
      "Proto\022\023\n\013request_key\030\001 \001(\003\022\022\n\nrequest_id" +
      "\030\002 \001(\005\022\017\n\007req_msg\030\003 \001(\t\022\014\n\004type\030\004 \001(\005B8\n" +
      "&com.baiyina.fmcommon.protocol.protobufB" +
      "\016FmRequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_FmReqProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_FmReqProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_FmReqProto_descriptor,
        new java.lang.String[] { "RequestKey", "RequestId", "ReqMsg", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
