server:
  port: 8081

spring:
  application:
    name: fm-router
  datasource:
    url: jdbc:mysql://47.113.203.123:3306/fm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 47.113.203.123
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      password: mypassword
  cache:
    type: redis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

eureka:
  instance:
    # eureka服务端的名称
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的查询服务和注册服务的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# enable swagger
springdoc:
  swagger-ui:
    enabled: true

fm:
  router:
    load_balancing:
      consistent_hash:
        virtual_node_num: 5

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN